

	<section id="main-wrapper">
		<div class="stories-container">
			<div class="inner-banner bp-rel">
				<div class="in-b-inner bp-rel" data-stellar-ratio="0.5">
					<img class="img-auto" src="dist/images/stories/banner-allrightreserved-grows-online-sales-with-new-ecommerce-platform.jpg" width="1440" height="699" alt="" title="">
					<div class="st-title bp-flex bp-ab pt10">
						<div class="container">
							<div class="row">
								<div class="col-sm-12 col-md-8 anim-content animUp">
									<div class="st-share">
										<h3 class="bp-set vm"><span>Retail, Manufacturing and Logistics</span></h3>
										<div class="bp-set vm bp-rel share-desktop-holder hidden-xs hidden-sm">
											<a class="bp-set vm auto-scroll st-like-share" href="#st-l-s-holder"><i class="fa fa-share-alt"></i></a>
										</div>
									</div>
									<h1>AllRightReserved: Grows Online Sales with New eCommerce Platform</h1>
									<div class="bp-set vm bp-rel hidden-md hidden-lg">
										<a class="bp-set vm auto-scroll st-like-share" href="#st-l-s-holder"><i class="fa fa-share-alt"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="in-module-holder pt5 pb5">

			  <div class="in-module st-background pt5 pb10">
					<div class="container-fluid">
						<div class="container anim-content animUp">
							<h2>Company profile</h2>
							<div class="row">
								<div class="col-sm-12 col-md-3 st-back-img">
									<img class="img-responsive mt2" src="dist/images/stories/stories-allrightreserved-grows-online-sales-with-new-ecommerce-platform-01.jpg" width="250" height="37" alt="" title="">
								</div>
								<div class="col-sm-12 col-md-9 in-par">
									<p>AllRightsReserved (ARR) is a Hong Kong based creative studio established in 2003, focusing on creative ideas, design, publishing and event management. </p>

									<p><strong>Bottleneck to handle unpredictable high traffic</strong><br>
									ARR has also been running product selling business online, and will launch individual eCommerce website when selling products of particular themes. ARR has been adopting monthly-subscribed eCommerce platforms which support features of product category, membership management, promotion management, status enquiry tracking, online payment, and linking to social media channels, however the platforms were unstable in terms of operation and unable to trace customer related information for getting insights.</p>

								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="in-module st-c-t-m-a pt5 pb10">
					<div class="container-fluid">
						<div class="container clearfix anim-content animUp">
							<div class="row">
								<div class="col-sm-12 col-md-7">
									<div class="st-img auto">
										<img class="img-auto" src="dist/images/stories/stories-allrightreserved-grows-online-sales-with-new-ecommerce-platform-02.jpg" width="548" height="369" alt="" title="">
									</div>
								</div>
								<div class="col-sm-12 col-md-5 in-par pt-md-3">
									<div class="pl2">
										<h2 class="mb0 pb3 mt5">Platform with complete functions</h2>
										<p>PCCW Solutions was selected by ARR to build a new eCommerce platform with high performance, providing end-to-end support from system design, platform development, system integration to consulting and training services. In addition to the enhanced performance, the new eCommerce platform offers a series of functions:</p>

										<ul class="bullet-list">
											<li> Site management</li>
											<li> Search engine optimization</li>
											<li> Marketing, promotions and conversion tools</li>
											<li> Catalog management</li>
											<li> Catalog and product browsing</li>
											<li> Checkout, payment and shipping</li>
											<li> Order management</li>
											<li> Customer accounts</li>
											<li> Web analytics and reporting</li>
											<li> Dashboard</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>

				<div class="in-module st-c-t-m-a pt0 pb5">
					<div class="container-fluid">
						<div class="container clearfix anim-content animUp">
							<div class="row">
								<div class="col-sm-12 col-md-5 in-par pb-md-3">
									<div class="pr2">
										<h2 class="mb0 pb3 mt5 mt">Instant deployment, quick result</h2>
										<p>Within one month after the new platform launch, the revenue generated by the online sales of Doraemon products has reached approximately HK$ 2 million. The new eCommerce platform can handle 30,000 page views per hour at maximum and can easily cater ARR’s future business needs:</p>
										<ul class="bullet-list">
											<li><strong>High flexibility and fast deployment</strong><br>
												additional website can be designed and built within a short period of time by using the provided templates of eCommerce platform, speeding up the product time-to-market.</li>
											<li><strong>High customizability</strong><br>
											the eCommerce platform is designed on module basis, which can easily be plugged in and modified with other modules such as Customer Relationship Management (CRM), loyalty program and analytics capabilities.</li>
											<li><strong>High scalability</strong><br> cloud hosting service and capability enable easy and quick system upgrade to deal with increasing transaction volume in future.</li>
										</ul>

									</div>
								</div>
								<div class="col-sm-12 col-md-7">
									<div class="st-img box-shadow">
										<img class="img-auto img-object-fit" src="dist/images/stories/stories-allrightreserved-grows-online-sales-with-new-ecommerce-platform-04.jpg" width="550" height="460" alt="" title="">
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>

				<div class="in-module so-full-pic pt5 pb5">
					<div class="container anim-content animUp">
						<div class="so-full-pic-holder">
							<img class="img-auto" src="dist/images/stories/stories-allrightreserved-grows-online-sales-with-new-ecommerce-platform-03.jpg"  alt="">
						</div>
					</div>
				</div>

				<div class="in-module download pt5">
					<div class="container-fluid download-inner gray pt5 pb5">
						<div class="container">
							<div class="row anim-content animUp">
								<div class="col-sm-12 col-md-8">
									<div class="row">
										<div class="col-sm-12 col-md-7 do-left anim-content animUp">
											<h2>Download Brochure</h2>
											<p>View the PDF version of this case study</p>
										</div>
									</div>
								</div>
								<div class="col-sm-12 col-md-4 clearfix anim-content animUp">
									<span class="button--bubble__container mt6 green pull-right">
										<a href="phase1/file_lib/AllRightReserved_Ltd_final_ENG.pdf" class="button button--bubble pccw-btn green">DOWNLOAD NOW</a>
										<span class="button--bubble__effect-container">
											<span class="circle top-left"></span>
											<span class="circle top-left"></span>
											<span class="circle top-left"></span>
											<span class="circle bottom-right"></span>
											<span class="circle bottom-right"></span>
											<span class="circle bottom-right"></span>
										</span>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="in-module anim-content pt5 animUp">
					<div id="st-l-s-holder" class="container-fluid st-l-s-holder blue-bg pt5 pb5">
						<div class="conatiner">
							<div class="like-share text-center anim-content animUp">
								<label class="bp-set vm">Like it? Share it</label>
								<a class="linkedin" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $url; ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"><i class="fa fa-linkedin"></i></a>
								<a class="facebook" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $url; ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"><i class="fa fa-facebook"></i></a>
								<a class="twitter" href="https://twitter.com/home?status=<?php echo $url; ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"><i class="fa fa-twitter"></i></a>
								<a class="googleplus" href="https://plus.google.com/share?url=<?php echo $url; ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"><i class="fa fa-google-plus"></i></a>
							</div>
						</div>
					</div>
				</div>



			</div>
		</div>
	</section>


